/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import { useCharacterAnimations } from "../contexts/CharacterAnimations";
import { useCharacterCustomization } from "../contexts/CharacterCustomizationContext";

function Woman(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/samba-dancer.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Aros"
            geometry={nodes.Aros.geometry}
            material={nodes.Aros.material}
            skeleton={nodes.Aros.skeleton}
          />
          <skinnedMesh
            name="Cara"
            geometry={nodes.Cara.geometry}
            material={nodes.Cara.material}
            skeleton={nodes.Cara.skeleton}
          />
          <skinnedMesh
            name="Cara001"
            geometry={nodes.Cara001.geometry}
            material={nodes.Cara001.material}
            skeleton={nodes.Cara001.skeleton}
          />
          <skinnedMesh
            name="Coleta"
            geometry={nodes.Coleta.geometry}
            material={nodes.Coleta.material}
            skeleton={nodes.Coleta.skeleton}
          />
          <skinnedMesh
            name="Flequillo"
            geometry={nodes.Flequillo.geometry}
            material={nodes.Flequillo.material}
            skeleton={nodes.Flequillo.skeleton}
          />
          <skinnedMesh
            name="Nariz"
            geometry={nodes.Nariz.geometry}
            material={nodes.Nariz.material}
            skeleton={nodes.Nariz.skeleton}
          />
          <skinnedMesh
            name="Ombligo"
            geometry={nodes.Ombligo.geometry}
            material={nodes.Ombligo.material}
            skeleton={nodes.Ombligo.skeleton}
          />
          <skinnedMesh
            name="Pelo"
            geometry={nodes.Pelo.geometry}
            material={nodes.Pelo.material}
            skeleton={nodes.Pelo.skeleton}
          />
          <skinnedMesh
            name="Personaje"
            geometry={nodes.Personaje.geometry}
            material={nodes.Personaje.material}
            skeleton={nodes.Personaje.skeleton}
          />
          <skinnedMesh
            name="Piercing1"
            geometry={nodes.Piercing1.geometry}
            material={nodes.Piercing1.material}
            skeleton={nodes.Piercing1.skeleton}
          />
          <skinnedMesh
            name="Sphere"
            geometry={nodes.Sphere.geometry}
            material={nodes.Sphere.material}
            skeleton={nodes.Sphere.skeleton}
          />
          <skinnedMesh
            name="Sphere001"
            geometry={nodes.Sphere001.geometry}
            material={nodes.Sphere001.material}
            skeleton={nodes.Sphere001.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/samba-dancer.gltf");

export default Woman;
